export type Locale = "en" | "ar";

export const dict: Record<Locale, Record<string, string>> = {
  en: {
    // Navbar
    "nav.how": "How it works",
    "nav.demos": "Demos",
    "nav.tryAgent": "Try the Agent",
    "nav.calculator": "ROI Calculator",
    "nav.why": "Why Mujeb",
    "nav.pricing": "Pricing",
    "nav.faq": "FAQ",
    "nav.bookDemo": "Try the Agent",
    "nav.toggleLang": "العربية",
    "nav.toggleTheme.light": "Switch to light mode",
    "nav.toggleTheme.dark": "Switch to dark mode",

    // Hero
    "hero.badge": "Next-Gen Voice AI for Modern Businesses",
    "hero.line1": "AI Voice Agents",
    "hero.line2": "That Never Miss a",
    "hero.rotate.0": "Lead",
    "hero.rotate.1": "Call",
    "hero.rotate.2": "Opportunity",
    "hero.rotate.3": "Customer",
    "hero.subtitle": "Turn missed calls into revenue with human-like AI voice agents available 24/7.",
    "hero.cta.book": "Try the Agent — Talk to It Live",
    "hero.cta.calc": "Calculate Your Lost Revenue",
    "hero.stat.0.v": "24/7", "hero.stat.0.l": "Availability",
    "hero.stat.1.v": "~2s", "hero.stat.1.l": "Response Time",
    "hero.stat.2.v": "92%", "hero.stat.2.l": "Accuracy",
    "hero.stat.3.v": "6x", "hero.stat.3.l": "More Bookings",

    // How it works
    "how.kicker": "How it Works",
    "how.title.a": "Live in",
    "how.title.b": "days",
    "how.title.c": ", not months",
    "how.s1.t": "Connect Your Voice Agent",
    "how.s1.d": "We set up your dedicated AI voice agent and connect it to your phone number — no technical work on your side.",
    "how.s2.t": "Train Your AI Agent",
    "how.s2.d": "We train your agent on your services, FAQs, and tone of voice — fluent, on-brand, ready in days.",
    "how.s3.t": "Start Capturing More Revenue",
    "how.s3.d": "Your AI handles every call instantly — booking, qualifying, and converting around the clock.",

    // Demos
    "demos.kicker": "Live Demos",
    "demos.title.a": "Hear our AI agents",
    "demos.title.b": "in action",
    "demos.subtitle": "Real call recordings across industries — booking, qualifying, and converting like a top human agent.",
    "demos.loadMore": "Load more demos",
    "demos.custom": "Get a custom demo for your business",

    // Calculator
    "calc.kicker": "Lost Revenue Calculator",
    "calc.title.a": "See how much you're",
    "calc.title.b": "losing",
    "calc.title.c": "every month",
    "calc.numbers": "Your numbers",
    "calc.missed": "Missed calls per month",
    "calc.deal": "Average deal value",
    "calc.conv": "Conversion rate",
    "calc.name": "Your name",
    "calc.email": "Work email",
    "calc.submit": "Recover Your Lost Revenue",
    "calc.snapshot": "Your loss snapshot",
    "calc.monthly": "Estimated Monthly Revenue Loss",
    "calc.perYear": "per year",
    "calc.lostLeads": "Lost Leads",
    "calc.potBookings": "Potential Bookings",
    "calc.missedYr": "Missed/Year",
    "calc.bookCall": "Talk to us about your numbers",

    // Why Mujeb
    "why.kicker": "Why Mujeb",
    "why.title.a": "Built for businesses that",
    "why.title.b": "refuse to miss",
    "why.f1.t": "Human-like Conversations",
    "why.f1.d": "Natural intonation, context awareness and zero robotic feel.",
    "why.f2.t": "Instant Deployment",
    "why.f2.d": "From signup to live calls in under 7 days.",
    "why.f3.t": "Multilingual in One Call",
    "why.f3.d": "Your agent switches between any language with all its local dialects — fluently within the same conversation, without ever asking the caller to repeat.",
    "why.f4.t": "Real-time Call Insights",
    "why.f4.d": "Live transcripts, sentiment, and outcomes for every call as it happens.",
    "why.f5.t": "24/7 Availability",
    "why.f5.d": "Never miss a call — including nights, weekends and holidays.",
    "why.f6.t": "Any Language, Every Dialect",
    "why.f6.d": "Trained to speak any language with its local dialects and accents — your customers feel understood from the very first second, in their own tongue.",

    // Pricing (flexible)
    "pricing.kicker": "Pricing",
    "pricing.flex.title.a": "Flexible pricing,",
    "pricing.flex.title.b": "built around your business",
    "pricing.flex.note": "There are no rigid packages. Every quote is tailored to your call volume, languages, integrations and the workflows you need — small business or enterprise.",
    "pricing.flex.badge": "Tailored Quote",
    "pricing.flex.heading": "A plan shaped around how your business actually runs.",
    "pricing.flex.desc": "Tell us about your operation and we'll send you a clear, fixed price within one business day — no surprises, no long contracts.",
    "pricing.flex.cta": "Request a Custom Quote",
    "pricing.flex.b1": "Priced to your monthly call volume",
    "pricing.flex.b2": "Any language with every local dialect in the same call",
    "pricing.flex.b3": "CRM, calendar & WhatsApp integrations included",
    "pricing.flex.b4": "Custom workflows, transfers & qualification",
    "pricing.flex.b5": "Scale up or down at any time",

    // Testimonials
    "tst.kicker": "Loved by operators",
    "tst.title.a": "Results that",
    "tst.title.b": "speak for themselves",

    // Metrics
    "met.0.v": "8.5K+", "met.0.l": "Calls handled",
    "met.1.v": "$210K", "met.1.l": "Revenue recovered",
    "met.2.v": "25+", "met.2.l": "Businesses scaled",
    "met.3.v": "4.9/5", "met.3.l": "Average rating",

    // FAQ
    "faq.kicker": "FAQ",
    "faq.title.a": "Everything you need to",
    "faq.title.b": "know",
    "faq.q1": "How quickly can my AI voice agent go live?",
    "faq.a1": "Setup typically takes 10 to 14 days end-to-end — including training on your services, voice tuning, number provisioning and testing before going live.",
    "faq.q2": "Will it sound robotic?",
    "faq.a2": "No. Mujeb uses ultra-realistic neural voices with natural pacing, interruption handling, and emotional tone.",
    "faq.q3": "Can the agent speak more than one language?",
    "faq.a3": "Yes — your agent is fully multilingual. It can switch fluently between any language (with all major dialects) within the same call, without asking the caller to repeat.",
    "faq.q4": "Can the agent handle bookings and follow-ups automatically?",
    "faq.a4": "Yes. The agent can book appointments on your calendar, send WhatsApp/SMS confirmations, qualify leads and trigger follow-up workflows automatically.",
    "faq.q5": "What happens if a call needs a human?",
    "faq.a5": "Your AI seamlessly transfers to a teammate or schedules a callback based on rules you define.",
    "faq.q6": "Is my data secure?",
    "faq.a6": "All calls are encrypted in transit and at rest. We're SOC 2 ready and GDPR compliant.",

    // CTA / contact
    "cta.title.a": "Stop losing revenue to",
    "cta.title.b": "missed calls",
    "cta.subtitle": "Tell us about your business and we'll show you exactly how much revenue your AI voice agent can recover — usually within one business day.",
    "cta.b1": "Free 30-minute strategy session",
    "cta.b2": "Tailored to your call volume & industry",
    "cta.b3": "No commitment, no pressure",
    "cta.f.name": "Full name",
    "cta.f.phone": "Phone",
    "cta.f.email": "Work email",
    "cta.f.company": "Company",
    "cta.f.companyOpt": "Optional",
    "cta.f.message": "Tell us about your business",
    "cta.f.messagePh": "Industry, call volume, what you'd like the agent to do...",
    "cta.f.submit": "Book My Free Demo",
    "cta.f.disclaimer": "By submitting, you agree to be contacted about your demo. We never share your info.",
    "cta.thanks": "Thanks",
    "cta.thanksDesc": "Your request is in. We'll reach out shortly to schedule your free demo.",
    "cta.toast.received.t": "Request received",
    "cta.toast.received.d": "We'll reach out within one business day.",
    "cta.toast.fail.t": "Submission failed",
    "cta.toast.fail.d": "Please try again.",
    "cta.toast.invalid.t": "Please check your inputs",

    // Sticky / footer
    "sticky.book": "Try the Agent",
    "sticky.whatsapp": "Chat on WhatsApp",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "AI voice agents that pick up every call — multilingual, instant, and always on-brand.",
    "footer.contact": "Contact",
    "footer.bookDemo": "Try the Agent",
    "footer.explore": "Explore",

    // Voice widget section
    "widget.kicker": "Try our voice agent live",
    "widget.badge": "Live AI Voice Agent",
    "widget.title.a": "Talk to a Mujeb",
    "widget.title.b": "voice agent right now",
    "widget.subtitle": "No forms, no waiting. Start a real conversation with our AI receptionist and hear it switch between languages on the fly.",
    "widget.cardTitle": "A real call, in real time",
    "widget.cardDesc": "Click the floating assistant in the corner of your screen to start a live voice conversation with the same kind of agent that will answer your customers' calls 24/7.",
    "widget.b1": "Multilingual in the same call — any language",
    "widget.b2": "Books, qualifies, and answers FAQs instantly",
    "widget.b3": "Hear what your customers will hear",
    "widget.tap": "Live voice demo",
  },
  ar: {
    // Navbar
    "nav.how": "كيف يعمل",
    "nav.demos": "نماذج صوتية",
    "nav.tryAgent": "جرّب الوكيل",
    "nav.calculator": "حاسبة العائد",
    "nav.why": "لماذا مُجيب",
    "nav.pricing": "الباقات",
    "nav.faq": "الأسئلة الشائعة",
    "nav.bookDemo": "جرّب الوكيل",
    "nav.toggleLang": "English",
    "nav.toggleTheme.light": "التبديل للوضع الفاتح",
    "nav.toggleTheme.dark": "التبديل للوضع الداكن",

    // Hero
    "hero.badge": "الجيل الجديد من الذكاء الصوتي لأعمال أكثر ذكاءً",
    "hero.line1": "وكلاء صوتيون أذكياء",
    "hero.line2": "لا يفوّتون لك",
    "hero.rotate.0": "عميلًا",
    "hero.rotate.1": "مكالمة",
    "hero.rotate.2": "فرصة",
    "hero.rotate.3": "صفقة",
    "hero.subtitle": "حوّل كل مكالمة فائتة إلى إيراد، مع وكيل صوتي بشري الإحساس يردّ خلال ثوانٍ، طوال اليوم وكل أيام الأسبوع.",
    "hero.cta.book": "جرّب الوكيل وتحدّث معه الآن",
    "hero.cta.calc": "احسب خسائرك الآن",
    "hero.stat.0.v": "24/7", "hero.stat.0.l": "في خدمتك دائمًا",
    "hero.stat.1.v": "~٢ث", "hero.stat.1.l": "سرعة الاستجابة",
    "hero.stat.2.v": "92%", "hero.stat.2.l": "دقة في الفهم",
    "hero.stat.3.v": "6x", "hero.stat.3.l": "حجوزات أكثر",

    // How
    "how.kicker": "كيف يعمل",
    "how.title.a": "جاهز للعمل خلال",
    "how.title.b": "أيام",
    "how.title.c": "، لا أشهر",
    "how.s1.t": "نربط وكيلك الصوتي",
    "how.s1.d": "نُجهّز وكيلك الصوتي المخصّص ونربطه برقم هاتفك — دون أي تعقيد تقني من جانبك.",
    "how.s2.t": "ندرّبه على عملك",
    "how.s2.d": "ندرّب الوكيل على خدماتك وأسئلتك المتكررة وهوية علامتك ليتحدّث بلسان شركتك تمامًا.",
    "how.s3.t": "تبدأ في تحقيق إيرادات أكبر",
    "how.s3.d": "وكيلك يردّ على كل مكالمة فورًا — يحجز ويؤهّل العملاء ويُحوّلهم إلى عملاء فعليين على مدار الساعة.",

    // Demos
    "demos.kicker": "نماذج صوتية حقيقية",
    "demos.title.a": "استمع لوكلائنا",
    "demos.title.b": "وهم يعملون",
    "demos.subtitle": "تسجيلات حقيقية من قطاعات متنوّعة — يحجزون ويؤهّلون ويُقنعون كأمهر موظف لديك.",
    "demos.loadMore": "اعرض المزيد من النماذج",
    "demos.custom": "اطلب نموذجًا مخصّصًا لنشاطك",

    // Calculator
    "calc.kicker": "حاسبة الإيرادات المفقودة",
    "calc.title.a": "اكتشف كم",
    "calc.title.b": "تخسر",
    "calc.title.c": "كل شهر فعليًا",
    "calc.numbers": "أدخل أرقامك",
    "calc.missed": "عدد المكالمات الفائتة شهريًا",
    "calc.deal": "متوسط قيمة الصفقة",
    "calc.conv": "نسبة التحويل المتوقّعة",
    "calc.name": "اسمك",
    "calc.email": "بريدك الإلكتروني",
    "calc.submit": "استرجع إيراداتك المفقودة الآن",
    "calc.snapshot": "ملخّص خسائرك",
    "calc.monthly": "خسارتك الشهرية المقدّرة",
    "calc.perYear": "سنويًا",
    "calc.lostLeads": "عملاء ضائعون",
    "calc.potBookings": "حجوزات محتملة",
    "calc.missedYr": "فرص مفقودة/سنة",
    "calc.bookCall": "تحدّث معنا حول أرقامك",

    // Why
    "why.kicker": "لماذا مُجيب",
    "why.title.a": "صُنع لمن",
    "why.title.b": "لا يقبل تفويت أي فرصة",
    "why.f1.t": "محادثات بإحساس بشري",
    "why.f1.d": "نبرة طبيعية، فهم عميق للسياق، وبدون أي إحساس بالصوت الآلي.",
    "why.f2.t": "إطلاق خلال أيام",
    "why.f2.d": "من اللحظة الأولى إلى مكالمات فعلية في أقل من 7 أيام.",
    "why.f3.t": "متعدّد اللغات في المكالمة الواحدة",
    "why.f3.d": "وكيلك ينتقل بين العربية والإنجليزية وأكثر بسلاسة داخل نفس المكالمة، دون أن يطلب من العميل أن يُعيد كلامه.",
    "why.f4.t": "تحليلات لحظية للمكالمات",
    "why.f4.d": "نصوص حية، قراءة لمشاعر العميل، ونتائج فورية لكل مكالمة بمجرد انتهائها.",
    "why.f5.t": "متاح 24/7 بلا انقطاع",
    "why.f5.d": "لن تفوّت أي مكالمة — في الليل، الإجازات، أو حتى الأعياد.",
    "why.f6.t": "أي لغة بكل لهجاتها",
    "why.f6.d": "مدرّب على التحدّث بأي لغة وبكل لهجاتها المحلية — يتحدّث مع عميلك بلسانه ولهجته، فيشعر بأنه يتحدّث مع شخص من بلده من أول ثانية.",

    // Pricing (flexible)
    "pricing.kicker": "الأسعار",
    "pricing.flex.title.a": "أسعار مرنة",
    "pricing.flex.title.b": "مُفصّلة على حسب نشاطك",
    "pricing.flex.note": "لا توجد باقات جامدة. كل عرض سعر يُصمَّم حسب حجم مكالماتك واللغات والتكاملات وسير العمل الذي تحتاجه — سواء كنت نشاطًا صغيرًا أو مؤسسة كبيرة.",
    "pricing.flex.badge": "عرض سعر مخصّص",
    "pricing.flex.heading": "خطة مُصمّمة على مقاس طريقة عمل شركتك فعلًا.",
    "pricing.flex.desc": "أخبرنا عن نشاطك وسنرسل لك عرض سعر واضح وثابت خلال يوم عمل واحد — بدون مفاجآت وبدون عقود طويلة.",
    "pricing.flex.cta": "اطلب عرض سعر مخصّص",
    "pricing.flex.b1": "السعر مبني على حجم مكالماتك الشهرية",
    "pricing.flex.b2": "كل اللهجات العربية + الإنجليزية في نفس المكالمة",
    "pricing.flex.b3": "تكاملات CRM والتقويم والواتساب مشمولة",
    "pricing.flex.b4": "سير عمل مخصّص وتحويل وتأهيل العملاء",
    "pricing.flex.b5": "زِد أو قلّل الباقة في أي وقت",

    // Testimonials
    "tst.kicker": "يحبّه أصحاب الأعمال",
    "tst.title.a": "نتائج",
    "tst.title.b": "تتحدّث عن نفسها",

    // Metrics
    "met.0.v": "+8.5K", "met.0.l": "مكالمة تمّت معالجتها",
    "met.1.v": "$210K", "met.1.l": "إيرادات مستردّة",
    "met.2.v": "+25", "met.2.l": "نشاط نموناه",
    "met.3.v": "4.9/5", "met.3.l": "متوسط التقييم",

    // FAQ
    "faq.kicker": "الأسئلة الشائعة",
    "faq.title.a": "كل ما تحتاج",
    "faq.title.b": "معرفته",
    "faq.q1": "كم يستغرق إطلاق وكيلي الصوتي؟",
    "faq.a1": "الإعداد الكامل يستغرق عادةً من 10 إلى 14 يومًا — يشمل التدريب على خدماتك، ضبط نبرة الصوت، توفير الرقم، والاختبار قبل الإطلاق الفعلي.",
    "faq.q2": "هل سيبدو صوته آليًا؟",
    "faq.a2": "لا. نستخدم أصواتًا عصبية فائقة الواقعية بإيقاع طبيعي وإدارة للمقاطعات ونبرة عاطفية.",
    "faq.q3": "هل يمكن للوكيل التحدّث بأكثر من لغة؟",
    "faq.a3": "نعم — وكيلك متعدد اللغات بالكامل. ينتقل بطلاقة بين العربية بكل لهجاتها الرئيسية والإنجليزية وغيرها داخل نفس المكالمة، دون أن يطلب من العميل أن يُعيد كلامه.",
    "faq.q4": "هل يقدر الوكيل يدير الحجوزات والمتابعات أوتوماتيكيًا؟",
    "faq.a4": "نعم. يحجز المواعيد على تقويمك، يرسل تأكيدات عبر الواتساب أو الرسائل، يؤهّل العملاء، ويشغّل سير عمل المتابعة بشكل تلقائي.",
    "faq.q5": "ماذا لو احتاجت المكالمة لتدخل بشري؟",
    "faq.a5": "ينتقل الوكيل بسلاسة لأحد أعضاء فريقك أو يحدّد موعد اتصال لاحق وفق قواعدك.",
    "faq.q6": "هل بياناتي آمنة؟",
    "faq.a6": "كل المكالمات مشفّرة أثناء النقل والتخزين، ونحن متوافقون مع SOC 2 و GDPR.",

    // CTA
    "cta.title.a": "أوقف نزيف إيراداتك من",
    "cta.title.b": "المكالمات الفائتة",
    "cta.subtitle": "أخبرنا عن نشاطك، وسنُريك بالأرقام كم يمكن لوكيلك الصوتي أن يستردّ — عادةً خلال يوم عمل واحد.",
    "cta.b1": "جلسة استراتيجية مجانية لمدة 30 دقيقة",
    "cta.b2": "مُصمّمة خصيصًا لحجم مكالماتك ومجال عملك",
    "cta.b3": "بدون التزام، وبدون أي ضغط",
    "cta.f.name": "الاسم بالكامل",
    "cta.f.phone": "رقم الهاتف",
    "cta.f.email": "البريد الإلكتروني للعمل",
    "cta.f.company": "اسم الشركة",
    "cta.f.companyOpt": "اختياري",
    "cta.f.message": "أخبرنا أكثر عن نشاطك",
    "cta.f.messagePh": "المجال، حجم المكالمات، وما تتوقّعه من الوكيل...",
    "cta.f.submit": "احجز عرضي المجاني الآن",
    "cta.f.disclaimer": "بإرسال طلبك، أنت توافق على تواصلنا معك بشأن العرض. بياناتك في أمان ولن نُشاركها مع أي طرف.",
    "cta.thanks": "شكرًا لك",
    "cta.thanksDesc": "وصلنا طلبك. سنتواصل معك قريبًا لتحديد موعد عرضك المجاني.",
    "cta.toast.received.t": "تم استلام الطلب",
    "cta.toast.received.d": "سنتواصل معك خلال يوم عمل واحد.",
    "cta.toast.fail.t": "فشل الإرسال",
    "cta.toast.fail.d": "حاول مرة أخرى.",
    "cta.toast.invalid.t": "يرجى مراجعة البيانات",

    // Sticky / footer
    "sticky.book": "جرّب الوكيل",
    "sticky.whatsapp": "راسلنا على واتساب",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.tagline": "وكلاء صوتيون بالذكاء الاصطناعي يردّون على كل مكالمة — بلسان عربي وإنجليزي، فورًا وبأسلوب علامتك.",
    "footer.contact": "تواصل معنا",
    "footer.bookDemo": "جرّب الوكيل",
    "footer.explore": "استكشف",

    // Voice widget
    "widget.kicker": "جرّب الوكيل الصوتي مباشرة",
    "widget.badge": "وكيل صوتي حيّ",
    "widget.title.a": "تحدّث مع وكيل",
    "widget.title.b": "مُجيب الصوتي الآن",
    "widget.subtitle": "بدون نماذج وبدون انتظار. ابدأ مكالمة حقيقية مع موظف الاستقبال الذكي، واستمع له وهو ينتقل بين العربية والإنجليزية بسلاسة.",
    "widget.cardTitle": "مكالمة حقيقية، في الوقت الفعلي",
    "widget.cardDesc": "اضغط على أيقونة المساعد العائمة في زاوية الشاشة لبدء مكالمة صوتية مع نفس نوع الوكيل الذي سيردّ على عملائك على مدار الساعة.",
    "widget.b1": "ثنائي اللغة في نفس المكالمة — عربي و إنجليزي",
    "widget.b2": "يحجز، يؤهّل، ويجيب على الأسئلة الشائعة فورًا",
    "widget.b3": "استمع لما سيسمعه عملاؤك تمامًا",
    "widget.tap": "تجربة صوتية مباشرة",
  },
};
